### ISSUE TITLE
Težava v funkciji rekurzija() 

### ISSUE THREAD

**Issue by zaloznikjan7** [evababnik/Robust-knapsack-problem#3]
Imava problem pri funkciji rekurzija() v datoteki solve_rkp.py v vrstici 249. Težava je v tem, da si funkcija vedno znova zapomne rešitve iz prejšnega seznama in potem rešitve samo še kopiči. Potrebovala bi torej vašo pomoč, da bi se seznam zopet nastavil na [], ko se funkcija znova zažene. Spodaj vidite primer, kjer se ob vsakem zagonu pripiše "print(seznam)" nato pa pokaže rešitev "(seznam stvari ki jih damo v nahrbtnik, optimalna vrednost predmetov)". Hvala za pomoč. 
Lep pozdrav, 
Jan Založnik
<img width="545" alt="Screenshot 2020-12-08 at 14 14 23" src="https://user-images.githubusercontent.com/57746808/101489938-f0d47b00-3961-11eb-9cf3-3a157ff00b35.png">

**Comment by jaanos** [comment]
Kolikor vidim, je težava v privzeti vrednosti parametra `resitev`:
https://github.com/evababnik/Robust-knapsack-problem/blob/a5e1379d494aa2350ebfacd51c79ec1f53cbc58b/python/koda_RKP.py#L233
Python si namreč samo enkrat shrani objekte, ki ustrezajo privzetim vrednostim parametrov - če funkcija tak objekt spremeni, se isti objekt uporabi kot privzeta vrednost pri naslednjem klicu funkcije. Namesto tega bo bolje za privzeti parameter nastaviti `None` in ga v funkciji ustrezno nadomestiti, npr.
```python
    def rekurzija(N, z_zvezdica, k_zvezdica, c_zvezdica, gama, w, maks_w, p, resitev=None):
        if resitev is None:
            resitev = []
        ...
```

**Comment by evababnik** [comment]
Najlepša hvala za odgovor!
Lep pozdrav,
Eva Babnik
